# Generated by Django 5.1.4 on 2024-12-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_image',
            field=models.ImageField(default='profile_images/default_user.jpg', upload_to='profile_images'),
        ),
    ]
